# Generated by Django 2.2.5 on 2020-02-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='teacher',
        ),
    ]
