# Generated by Django 2.2.5 on 2020-02-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0002_auto_20200207_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='teacher',
            new_name='staff',
        ),
    ]
